services:
  # Web service для веб-интерфейса администратора
  - type: web
    name: language-mirror-admin
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_MODE
        value: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

  # Web service для бота в режиме webhook
  - type: web
    name: language-mirror-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run_webhook.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_MODE
        value: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false